# Generated by Django 4.2.1 on 2024-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enposthead',
            old_name='title_eng',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_visibility',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='enposthead',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enposthead',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='home_page_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uaposthead',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uaposthead',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='enposthead',
            name='preview_text_eng',
            field=models.TextField(blank=True, null=True),
        ),
    ]
