# Generated by Django 4.2.1 on 2024-01-31 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=255, verbose_name='Tender ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('product_code', models.CharField(max_length=50, verbose_name='Product Code')),
                ('purchase_code', models.CharField(max_length=50, verbose_name='Purchase Code')),
                ('prozorro_id', models.CharField(max_length=50, unique=True, verbose_name='ProZorro ID')),
                ('date', models.DateField(db_index=True, verbose_name='Tender Date')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.BooleanField(default=False, verbose_name='Visibility')),
                ('file', models.FileField(upload_to='files/', verbose_name='File Field')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_name', models.CharField(max_length=255, unique=True)),
                ('en_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='procurement.procurement')),
            ],
        ),
        migrations.CreateModel(
            name='TenderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='procurement.procurement')),
            ],
        ),
        migrations.CreateModel(
            name='TenderPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='procurement.procurement')),
            ],
        ),
        migrations.CreateModel(
            name='ProcuringEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_id', models.CharField(max_length=8, null=True)),
                ('identifier_scheme', models.CharField(max_length=10, null=True)),
                ('identifier_name', models.CharField(max_length=255, null=True)),
                ('country_name', models.CharField(max_length=32, null=True)),
                ('postal_code', models.CharField(max_length=5, null=True)),
                ('region', models.CharField(max_length=32, null=True)),
                ('locality', models.CharField(max_length=32, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contact_email', models.CharField(max_length=62, null=True)),
                ('contact_phone', models.CharField(max_length=12, null=True)),
                ('contact_url', models.CharField(max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255, null=True)),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procuring_entity', to='procurement.procurement')),
            ],
        ),
        migrations.AddField(
            model_name='procurement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.unit', verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('classification_id', models.CharField(max_length=10, null=True)),
                ('classification_scheme', models.CharField(max_length=10, null=True)),
                ('classification_description', models.CharField(max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit_name', models.CharField(max_length=255, null=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.procurement')),
            ],
        ),
    ]
